### PR TITLE
Svg headers update

### PR DESCRIPTION
**Pull request by superfrank**
## What does this change?
Headers placed in titlepiece (not available as a font, so SVG created for each). This was a design request from Breuer. My only concern is, if removing a H1 how does this affect SEO?

Maybe some more ammunition for us getting the rights for titlepiece (@paperboyo)

Changes already live:
https://www.theguardian.com/info/ng-interactive/2016/dec/07/sign-up-for-the-flyer
https://www.theguardian.com/info/ng-interactive/2017/jan/12/sign-up-for-the-guardian-opinion-email
https://www.theguardian.com/info/ng-interactive/2016/dec/05/sign-up-for-weekend-reading

## Screenshots
image
image
image

## Request for comment
@joelochlann @lmath

### CODE REVIEW

**Comment by davidfurey** [comment]
From an Accessibility point-of-view this is a significant step backwards, but maybe you can mitigate this by adding `<span class="u-h">The Flyer</span>`, which seems to be what we do for the main theguardian text

**Comment by paperboyo** [comment]
As discussed ad nuseam, we should really be moving away from more usage of Titlepiece. The extended character set and features that all our fonts enjoy were never drawn for this font.

Section names in the paper may _seem safe_, but I thought we already agreed to swap it for (very similar) Egyptian Semibold in Apps to avoid e.g. this:

screenshot_20170221-104853

Here is a comparison - Semibold is indeed different, but only because you can see them side by side 😉. Semibold should soon be available on dotcom in extended character set - currently - it’s only ASCII:

titlepiece-vs -semibold

I would expect no new designs and usages of Titlepiece (incl. the secret ones), to be honest and, ideally, its slow death beyond the masthead logo (also - to protect branding). The only alternative for the safe future with Titlepiece would be to commission a proper overhaul of the font.

Also, it’s 2017 and text-as-image should be avoided whenever possible.

Just my 2gr, obv!

**Comment by superfrank** [comment]
You don't need to show me the difference between the two Mateusz - was displaying it in semi bold previously!

AB has requested it specifically and this is for brand names, i.e. these emails: https://www.theguardian.com/email-newsletters so issues around extended characters etc shouldn't become a problem.

Will include the span change if that'll help SEO, cheers David.

**Comment by paperboyo** [comment]
> You don't need to show me the difference between the two Mateusz - was displaying it in semi bold previously!

I know, I know. It was more for myself than anyone else :)

> so issues around extended characters etc shouldn't become a problem

Until they do. This is exactly about encroachment, using it in more and more places, that can suddenly bite us back. Just wanted to make that point, humbly as always, [emoji overload].

**Comment by joelochlann** [comment]
👍  Seems OK to me. Although it's seems a shame to have to use SVGs for these, both for the accessibility reasons @davidfurey mentioned and also for maintainability - i.e. un-semantic blobs of SVG in the template, and extra CSS including magic numbers (@superfrank's favourite phrase) for height & width

**Pull request merged**
